export enum Role {
    REGISTRAR = 'REGISTRAR',
    RESIDENT_DIRECTOR = 'RESIDENT_DIRECTOR',
    DEAN = 'DEAN',
    HEAD_OF_DEPARTMENT = 'HEAD_OF_DEPARTMENT',
    STAFF = 'STAFF',
    STUDENT = 'STUDENT',
}
